image: golang:1.12

before_script:
  - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
  - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
  - apt-get update -yq
  - apt-get install -y heroku-toolbelt

stages:
  - vetting
  - tests
  - deploy

lint:
  stage: vetting
  script:
    - go get -u golang.org/x/lint/golint
    - golint -set_exit_status ./...

unitests:
  stage: tests
  script:
    - go get -u github.com/gorilla/mux
    - go test ./...
    - go vet

deploying:
  stage: deploy
  script:
    - heroku git:remote -a team-project-testing
    - echo $email
    - heroku logs --tail
    - git remote -v
  #only:
    #- master
