image: golang:1.12

before_script:
  - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
  - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
  - apt-get update -yq
  - apt-get install -y heroku-toolbelt

stages:
  #- vetting
  #- tests
  - deploy

#lint:
  #stage: vetting
  #script:
   # - go get -u golang.org/x/lint/golint
   # - golint -set_exit_status ./...

#unitests:
  #stage: tests
  #script:
  #  - go get -u github.com/gorilla/mux
   # - go test ./...
   # - go vet

deploying:
  stage: deploy
  script:
    #- heroku git:remote -a team-project-testing
    #- git remote add heroku https://heroku:35ce1746-94bf-4d66-a729-5778d2987b9f@git.heroku.com/team-projectv1.git
    - git checkout -b publish-to-heroku
    - git commit --allow-empty -m "Test pushing to heroku"
    - git branch -v
    - git push https://heroku:35ce1746-94bf-4d66-a729-5778d2987b9f@git.heroku.com/team-projectv1.git publish-to-heroku:master
  #only:
    #- master
